package model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "cart") // Deze klasse wordt als entity cart in database gemaakt
public class Cart {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // Autogenerated attribute id

	@OneToOne(mappedBy = "cart")
	private Account account; // One-to-one relatie met account, account_id is de FK

	@ManyToMany
	@JoinTable(name = "cart_product", joinColumns = @JoinColumn(name = "cart_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "product_id", referencedColumnName = "id"))
	private List<Product> products; //Many_to_many relatie met product, de koppeltable is cart_product

	//Deze constructor is verplicht om informatie uit te database te halen
	public Cart() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	//Er wordt give i.p.v get gebruikt om geen data van account direct te weergeven
	public Account giveAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	//Er wordt give i.p.v get gebruikt om geen data van products direct te weergeven
	public List<Product> giveProducts() {
		return products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}
}