package model;

import java.util.*;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

@Entity
@Table(name = "category") // Deze klasse wordt als entity category in database gemaakt
public class Category {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // Autogenerated attribute id
	private String name;
	private String description;
	private String imageId;

	@ManyToMany(mappedBy = "categories")
	private List<Product> products; //Many_to_many relatie met product, de koppeltable is product_category

	public Category(String name, String description, String imageId) {
		this.name = name;
		this.description = description;
		this.imageId = imageId;
	}
	
	//Deze constructor is verplicht om informatie uit te database te halen
	public Category() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImageId() {
		return imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	//Er wordt give i.p.v get gebruikt om geen data van products direct te weergeven
	public List<Product> giveProducts() {
		return products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}
}