package model;

import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.rest.core.annotation.RestResource;

@Entity
@Table(name = "checkout") // Deze klasse wordt als entity checkout in database gemaakt
public class Checkout {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // Autogenerated attribute id
	private String pay_method; //Moet een van die waarden (Cash, Creditcard, Visacard, iDeal, Paypal)
	private Long offer_code; //Hiermee wordt discount_id bedoeld
	private Date pay_date;  //Het moet vandag zijn

	@ManyToOne
	@JoinColumn(name = "account_id", nullable = false)
	@RestResource(path = "checkoutAccount", rel = "account")
	private Account account; // Many-to-one relatie met account, account_id is de FK

	@ManyToMany
	@JoinTable(name = "checkout_product", joinColumns = @JoinColumn(name = "checkout_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "product_id", referencedColumnName = "id"))
	private List<Product> products; //Many_to_many relatie met product, de koppeltable is checkout_product

	public Checkout(String pay_method, Long offer_code, Date pay_date) {
		this.pay_method = pay_method;
		this.offer_code = offer_code;
		this.pay_date = pay_date;
	}

	//Deze constructor is verplicht om informatie uit te database te halen
	public Checkout() {

	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPay_method() {
		return pay_method;
	}

	public void setPay_method(String pay_method) {
		this.pay_method = pay_method;
	}

	public Long getOffer_code() {
		return offer_code;
	}

	public void setOffer_code(Long offer_code) {
		this.offer_code = offer_code;
	}

	public Date getPay_date() {
		return pay_date;
	}

	public void setPay_date(Date pay_date) {
		this.pay_date = pay_date;
	}

	//Er wordt give i.p.v get gebruikt om geen data van account direct te weergeven
	public Account giveAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	//Er wordt give i.p.v get gebruikt om geen data van products direct te weergeven
	public List<Product> giveProducts() {
		return products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

}
