package model;

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.springframework.data.rest.core.annotation.RestResource;

@Entity
@Table(name = "checkout") // Deze klasse wordt als entity checkout in database gemaakt
public class Checkout {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // Autogenerated attribute id
	private String pay_method; // Moet een van die waarden (Cash, Creditcard, Visacard, iDeal, Paypal)
	private Long offer_code; // Hiermee wordt discount_id bedoeld
	private Date pay_date; // Het moet vandag zijn

	@OneToOne
	@JoinColumn(name = "order_id")
	@RestResource(path = "checkoutOrder", rel = "order")
	private Order order; // One-to-one relatie met order, order_id is de FK

	public Checkout(String pay_method, Long offer_code, Date pay_date) {
		this.pay_method = pay_method;
		this.offer_code = offer_code;
		this.pay_date = pay_date;
	}

	// Deze constructor is verplicht om informatie uit te database te halen
	public Checkout() {

	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPay_method() {
		return pay_method;
	}

	public void setPay_method(String pay_method) {
		this.pay_method = pay_method;
	}

	public Long getOffer_code() {
		return offer_code;
	}

	public void setOffer_code(Long offer_code) {
		this.offer_code = offer_code;
	}

	public Date getPay_date() {
		return pay_date;
	}

	public void setPay_date(Date pay_date) {
		this.pay_date = pay_date;
	}

	// Er wordt give i.p.v get gebruikt om geen data van order direct te weergeven
	public Order giveOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

}
