package model;

import java.util.*;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.rest.core.annotation.RestResource;

@Entity
@Table(name = "order_table") // Deze klasse wordt als order_table cart in database gemaakt omdat order woord is gereserveerd voor het systeem
public class Order {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // Autogenerated attribute id
	private Date date;
	private double total_price;

	@ManyToOne
	@JoinColumn(name = "account_id", nullable = false)
	@RestResource(path = "orderAccount", rel = "account")
	private Account account; // Many-to-one relatie met account, account_id is de FK

	@ManyToMany
	@JoinTable(name = "order_product", joinColumns = @JoinColumn(name = "order_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "product_id", referencedColumnName = "id"))
	private List<Product> products; //Many_to_many relatie met product, de koppeltable is order_product

	public Order(Date date, double total_price) {
		this.date = date;
		this.total_price = total_price;
	}

	//Deze constructor is verplicht om informatie uit te database te halen
	public Order() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public double getTotal_price() {
		return total_price;
	}

	public void setTotal_price(double total_price) {
		this.total_price = total_price;
	}

	//Er wordt give i.p.v get gebruikt om geen data van account direct te weergeven
	public Account giveAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	//Er wordt give i.p.v get gebruikt om geen data van products direct te weergeven
	public List<Product> giveProducts() {
		return products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}
}