package model;

import java.util.*;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

@Entity
@Table(name = "product") // Deze klasse wordt als entity product in database gemaakt
public class Product {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // Autogenerated attribute id
	private String name;
	private String description;
	private double normal_price;
	private String discount_price;
	private boolean available;
	private String imageId;

	@ManyToMany
	@JoinTable(name = "product_category", joinColumns = @JoinColumn(name = "product_id", referencedColumnName = "id"), inverseJoinColumns = @JoinColumn(name = "category_id", referencedColumnName = "id"))
	private List<Category> categories; // Many_to_many relatie met category, de koppeltable is product_category

	@ManyToMany(mappedBy = "products")
	private List<Cart> carts; // Many_to_many relatie met carts, de koppeltable is cart_product

	@ManyToMany(mappedBy = "products")
	private List<Discount> discounts; // Many_to_many relatie met discount, de koppeltable is discount_product

	@ManyToMany(mappedBy = "products")
	private List<Order> orders; // Many_to_many relatie met order, de koppeltable is order_product

	public Product(String name, String description, double normal_price, String discount_price, boolean available,
			String imageId) {
		this.name = name;
		this.description = description;
		this.normal_price = normal_price;
		this.discount_price = discount_price;
		this.available = available;
		this.imageId = imageId;
	}

	// Deze constructor is verplicht om informatie uit te database te halen
	public Product() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getNormal_price() {
		return normal_price;
	}

	public void setNormal_price(double normal_price) {
		this.normal_price = normal_price;
	}

	public String getDiscount_price() {
		return discount_price;
	}

	public void setDiscount_price(String discount_price) {
		this.discount_price = discount_price;
	}

	public boolean isAvailable() {
		return available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public String getImageId() {
		return imageId;
	}

	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	// Er wordt give i.p.v get gebruikt om geen data van orders direct te weergeven
	public List<Order> giveOrders() {
		return orders;
	}

	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}

	// Er wordt give i.p.v get gebruikt om geen data van discounts direct te
	// weergeven
	public List<Discount> giveDiscounts() {
		return discounts;
	}

	public void setDiscounts(List<Discount> discounts) {
		this.discounts = discounts;
	}

	// Er wordt give i.p.v get gebruikt om geen data van categories direct te
	// weergeven
	public List<Category> giveCategories() {
		return categories;
	}

	public void setCategories(List<Category> categories) {
		this.categories = categories;
	}

	// Er wordt give i.p.v get gebruikt om geen data van carts direct te weergeven
	public List<Cart> giveCarts() {
		return carts;
	}

	public void setCarts(List<Cart> carts) {
		this.carts = carts;
	}

}