package model;

import java.util.*;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "role") // Deze klasse wordt als entity role in database gemaakt
public class Role{

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // Autogenerated attribute id
	private String name;
	private String description;

	@OneToMany(mappedBy = "role", fetch = FetchType.EAGER)
	private List<Account> accounts; // One_to_many relatie met account, role_id is de FK in account

	public Role(String name, String description) {
		this.name = name;
		this.description = description;
	}

	//Deze constructor is verplicht om informatie uit te database te halen
	public Role() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	//Er wordt give i.p.v get gebruikt om geen data van accounts direct te weergeven
	public List<Account> giveAccounts() {
		return accounts;
	}

	public void setAccounts(List<Account> accounts) {
		this.accounts = accounts;
	}
}